INSERT INTO u_stages (name) VALUES
('75m'),
('Battlefield'),
('Big Battlefield'),
('Boxing Ring'),
('Bridge of Eldin'),
('Castle Siege'),
('Coliseum'),
('Delfino Plaza'),
('Duck Hunt'),
('Final Destination'),
('Flat Zone X'),
('Gamer'),
('Garden of Hope'),
('Gaur Plain'),
('Halberd'),
('Jungle Hijinxs'),
('Kalos Pokémon League'),
('Kongo Jungle 64'),
('Luigi''s Mansion'),
('Lylat Cruise'),
('Mario Circuit'),
('Mario Circuit (Brawl)'),
('Mario Galaxy'),
('Miiverse'),
('Mushroom Kingdom U'),
('Norfair'),
('Onett'),
('Orbital Gate Assault'),
('Pac-Land'),
('Palutena''s Temple'),
('Pilotwings'),
('Pokémon Stadium 2'),
('Port Town Aero Dive'),
('Pyrosphere'),
('Skyloft'),
('Skyworld'),
('Smashville'),
('Temple'),
('The Great Cave Offensive'),
('Town and City'),
('Wii Fit Studio'),
('Wily Castle'),
('Windy Hill Zone'),
('Woolly World'),
('Wrecking Crew'),
('Wuhu Island'),
('Yoshi''s Island')
;

INSERT INTO u_characters (name) VALUES
('Bowser'),
('Bowser Jr.'),
('Captain Falcon'),
('Charizard'),
('Dark Pit'),
('Diddy Kong'),
('Donkey Kong'),
('Dr. Mario'),
('Duck Hunt'),
('Falco'),
('Fox'),
('Ganondorf'),
('Greninja'),
('Ike'),
('Jigglypuff'),
('King Dedede'),
('Kirby'),
('Link'),
('Little Mac'),
('Lucario'),
('Lucina'),
('Luigi'),
('Mario'),
('Marth'),
('Mega Man'),
('Meta Knight'),
('Mii Brawler'),
('Mii Gunner'),
('Mii Swordfighter'),
('Mr. Game & Watch'),
('Ness'),
('Olimar'),
('Pac-Man'),
('Palutena'),
('Peach'),
('Pikachu'),
('Pit'),
('R.O.B.'),
('Robin'),
('Rosalina & Luma'),
('Samus'),
('Sheik'),
('Shulk'),
('Sonic'),
('Toon Link'),
('Villager'),
('Wario'),
('Wii Fit Trainer'),
('Yoshi'),
('Zelda'),
('Zero Suit Samus'),
('Mewtwo')
;

INSERT INTO u_players (name) VALUES
('John'),
('Lowell'),
('Luke'),
('Brett')
;
